const prettierConfig = {
    printWidth: 80,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    singleQuote: true,
    quoteProps: 'as-needed',
    jsxSingleQuote: false,
    trailingComma: 'es5',
    bracketSpacing: true,
    bracketSameLine: false,
    arrowParens: 'always',
    requirePragma: false,
    insertPragma: false,
    proseWrap: 'preserve',
    htmlWhitespaceSensitivity: 'css',
    endOfLine: 'lf',
    embeddedLanguageFormatting: 'auto',
    singleAttributePerLine: false,
    plugins: ['@ianvs/prettier-plugin-sort-imports'],

    importOrder: [
        '^(node)$',
        '',
        '<THIRD_PARTY_MODULES>',

        '',
        '^@/config/(.*)$',
        '',
        '^@/middlewares/(.*)$',
        '',
        '^@/plugins/(.*)$',
        '',
        '^@/routes/(.*)$',
        '',
        '^@/controllers/(.*)$',
        '',
        '^@/services/(.*)$',
        '',
        '^@/repositories/(.*)$',
        '',
        '^@/validators/(.*)$',
        '',
        '^@/utils/(.*)$',
        '',
        '^@/interfaces/(.*)$',
        '',
        '^[./]',
    ],
};

export default prettierConfig;
